CREATE PROFESOR (
	DNI VARCHAR(9), NOT NULL,
	NOMBRE VARCHAR(30), NOT NULL,
	APELLIDO1 VARCHAR(50) NOT NULL,
	APELLIDO2 VARCHAR(50) NULL, 
	TIPO VARCHAR2(20) NOT NULL,
	CONSTRAINT pk_profesor PRIMARY KEY (DNI)
	);

CREATE TABLE ASIGNATURA(
	CODASIG NUMBER(3),
	NOMBRE VARCHAR(30),
	NUMHORAS NUMBER(3),
	------------------------
	-- CAMPO CREADO PARA ALMACENAR FOREIGN KEY
	DNI_PROFESOR VARCHAR(9),
	------------------------
	CONSTRAINT pk_asignatura PRIMARY KEY (CODASIG)
	CONSTRAINT fk_asignatura FOREIGN KEY (DNI_PROFESOR) 
	REFERENCES PROFESOR(DNI)
	);