CREATE TABLE PROFESOR(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(30),
	APELLIDO1 VARCHAR2(30),
	APELLIDO2 VARCHAR2(30) NULL,
	DIRECCION VARCHAR2(50),
	CUENTA VARCHAR2(26),
	TELEFONO NUMBER(9),
	CONSTRAINT pk_profesor PRIMARY KEY(DNI)
);
CREATE TABLE CICLOFORM(
	CODCICLO NUMBER(3),
	NOMBRE VARCHAR2(30),
	TIPO VARCHAR2(20),
	CONSTRAINT pk_cicloform PRIMARY KEY (CODCICLO)
);
CREATE TABLE ASIGNATURA(
	CODASIG NUMBER(3),
	NOMBRE VARCHAR(30),
	NUMHORAS NUMBER(3),
	CONSTRAINT pk_asignatura PRIMARY KEY (CODASIG),
	CONSTRAINT fk_ciclo FOREIGN KEY (CODCICLOFORM) REFERENCES CICLOFORM(CODCICLO),
	CONSTRAINT fk_prof FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESOR(DNI),
);
CREATE TABLE IDIOMA(
	CODIDIOMA VARCHAR2(20),
	DESCRIPCION VARCHAR2(30),
	CONSTRAINT pk_idioma PRIMARY KEY (CODIDIOMA)
);	
CREATE TABLE IDIOMASPROF(
	CODIDIOMA VARCHAR2(30),
	DNI_PROFESOR VARCHAR2(9),
	CONSTRAINT pk_idiomasprof PRIMARY KEY(CODIDIOMA, DNI_PROFESOR),
	CONSTRAINT fk_idioma FOREIGN KEY (CODIDIOMA) REFERENCES IDIOMA (CODIDIOMA)
);
CREATE TABLE ALUMNO(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(30),
	APELLIDO1 VARCHAR2(30),
	APELLIDO2 VARCHAR2(30) NULL,
	DIRECCION VARCHAR2(50),
	TELEFONO NUMBER(9),
	CODIDIOMA VARCHAR2(20) NULL,
	CONSTRAINT pk_alumno PRIMARY KEY(DNI),
	CONSTRAINT fk_idioma2 FOREIGN KEY(CODIDIOMA) REFERENCES IDIOMA (CODIDIOMA)
);	
CREATE TABLE MATRICULA(
	CODASIG NUMBER(3),
	DNI_ALUMNO VARCHAR2(9),
	CONSTRAINT pk_matricula PRIMARY KEY (CODASIG,DNI_ALUMNO),
	CONSTRAINT fk_asig FOREIGN KEY(CODASIG) REFERENCES ASIGNATURA(CODASIG),
	CONSTRAINT fk_alumno FOREIGN KEY (DNI_ALUMNO) REFERENCES ALUMNO (DNI)
);