CREATE TABLE SEDE(
	CodSede NUMBER(3),
	Nombre VARCHAR2(30),
	Direccion VARCHAR2(50),
	CONSTRAINT pk_SEDE PRIMARY KEY (CodSede)
);
CREATE TABLE DEPARTAMENTO(
	CodDep NUMBER(3),
	Nombre VARCHAR(30),
	Ubicacion NUMBER(3),
	CodSede NUMBER(3),	CONSTRAINT pk_DEPARTAMENTO PRIMARY KEY (CodDep, CodSede),
	CONSTRAINT fk_SEDE FOREIGN KEY (CodSede) REFERENCES SEDE(CodSede)
);
CREATE TABLE PROGRAMADOR(
	Secuencia NUMBER(5),
	Nombre VARCHAR2(30),
	Apellido1 VARCHAR2(30),
	Apellido2 VARCHAR2(30) NULL,
	Direccion VARCHAR2(50),
	Cuenta VARCHAR2(26),
	Telefono NUMBER(9),
	Tipo VARCHAR(20),
	CodSede NUMBER(3),
	CodDep NUMBER(3),
	SecuenciaMentor NUMBER(5)
	CONSTRAINT pk_PROGRAMADOR PRIMARY KEY (Secuencia, CodSede, CodDep),
	CONSTRAINT fk_DEPARTAMETO FOREIGN KEY (CodDep, CodSede) REFERENCES DEPARTAMENTO(CodDep, CodSede),
	CONSTRAINT fk_PROGRAMADOR1 FOREIGN KEY (SecuenciaMentor) REFERENCES PROGRAMADOR(Secuencia)
);
CREATE TABLE EQUIPO(
	CodEquipo NUMBER(3),
	Descripcion VARCHAR (50),
	Secuencia NUMBER(5),
	CodDep NUMBER(3),
	CodSede NUMBER(3),
	CONSTRAINT pk_EQUIPO1 PRIMARY KEY (CodEquipo),
	CONSTRAINT fk_PROGRAMADOR2 FOREIGN KEY (Secuencia, CodDep, CodSede) 
	REFERENCES PROGRAMADOR(Secuencia, CodDep, CodSede)
);
CREATE TABLE EQUIPOPROG(
	Secuencia NUMBER(5),
	CodSede NUMBER(3),
	CodDep NUMBER(3),
	CodEquipo NUMBER(3),
	CONSTRAINT pk_EQUIPOPROG PRIMARY KEY (Secuencia, CodSede, CodDep, CodEquipo),
	CONSTRAINT fk_EQUIPO2 FOREIGN KEY (CodEquipo) REFERENCES EQUIPO(CodEquipo),
	CONSTRAINT fk_PROGRAMADOR3 FOREIGN KEY (Secuencia, CodSede, CodDep) 
	REFERENCES PROGRAMADOR(Secuencia, CodSede, CodDep)
);
CREATE TABLE PROYECTO(
	FechaIni DATE,
	Descripcion VARCHAR2(50),
	FechaFin DATE NULL,
	CodEquipo NUMBER(3),
	FechaIniSubProy DATE,
	CONSTRAINT pk_PROYECTO PRIMARY KEY (FechaIni, CodEquipo),
	CONSTRAINT fk_EQUIPO3 FOREIGN KEY (CodEquipo) REFERENCES EQUIPO(CodEquipo),
	CONSTRAINT fk_PROYECTO1 FOREIGN KEY (FechaIniSubProy) REFERENCES PROYECTO(FechaIni)
);
