CREATE TABLE PERSONA(
	DNI VARCHAR2(9),
	Nombre VARCHAR2(30),
	Apellido1 VARCHAR2(30),
	Apellido2 VARCHAR2(30) NULL,
	Tipo VARCHAR2(5),
	CONSTRAINT pk_PERSONA PRIMARY KEY (DNI)
);
CREATE TABLE BIBLIOTECARIO(
	DNIBibliotecario VARCHAR2(9),	
	CONSTRAINT pk_BIBLIOTECARIO PRIMARY KEY (DNIBibliotecario),
	CONSTRAINT fk_PERSONA1 FOREIGN KEY (DNIBibliotecario) REFERENCES PERSONA(DNI)
);
CREATE TABLE SOCIO(
	DNISocio VARCHAR2(9),	
	CONSTRAINT pk_SOCIO PRIMARY KEY (DNISocio),
	CONSTRAINT fk_PERSONA2 FOREIGN KEY (DNISocio) REFERENCES PERSONA(DNI)
);
CREATE TABLE AUTOR(
	DNIAutor VARCHAR2(9),	
	CONSTRAINT pk_AUTOR PRIMARY KEY (DNIAutor),
	CONSTRAINT fk_PERSONA3 FOREIGN KEY (DNIAutor) REFERENCES PERSONA(DNI)
);
CREATE TABLE TEMATICA(
	Tematica VARCHAR2 (30),
	CONSTRAINT pk_TEMATICA PRIMARY KEY (Tematica)
);
CREATE TABLE LIBRO(
	ISBN VARCHAR2 (13),
	Título VARCHAR (100),
	NumPaginas VARCHAR (5),
	TematicaLibro VARCHAR (30),
	CONSTRAINT pk_LIBRO PRIMARY KEY (ISBN),
	CONSTRAINT fk_LIBRO1 FOREIGN KEY (TematicaLibro) REFERENCES TEMATICA(Tematica)
);
CREATE TABLE AUTORLIBRO(
	ISBN VARCHAR2 (13),
	DNIAutor VARCHAR2(9),
	CONSTRAINT pk_AUTORLIBRO PRIMARY KEY (ISBN, DNIAutor),
	CONSTRAINT fk_AUTOR1 FOREIGN KEY (DNIAutor) REFERENCES AUTOR(DNIAutor),
	CONSTRAINT fk_LIBRO1 FOREIGN KEY (ISBN) REFERENCES LIBRO(ISBN)
);
CREATE TABLE PRESTAMOS(
	DNIBibliotecario VARCHAR2(9),	
	DNISocio VARCHAR2(9),	
	ISBN VARCHAR2 (13),
	CONSTRAINT pk_PRESTAMO PRIMARY KEY (DNIBibliotecario, DNISocio, ISBN),
	CONSTRAINT fk_BIBLIOTECARIO1 FOREIGN KEY (DNIBibliotecario) 
	REFERENCES BIBLIOTECARIO(DNIBibliotecario),
	CONSTRAINT fk_SOCIO1 FOREIGN KEY (DNISocio)
	REFERENCES SOCIO(DNISocio),
	CONSTRAINT fk_LIBRO2 FOREIGN KEY (ISBN)
	REFERENCES LIBRO(ISBN)
);